"""Add staff_skill column to staff table

Revision ID: 893f9c27fbd0
Revises: e2be5f02cfe4
Create Date: 2025-01-28 12:17:56.659621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893f9c27fbd0'
down_revision = 'e2be5f02cfe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_skill', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('staff_skill')

    # ### end Alembic commands ###
